name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - uses: advanced-security/codeql-bundle-action/download-bundle@v2
      id: download-bundle
      with:
        tag: "latest"  

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
      
    - uses: advanced-security/codeql-bundle-action/create-bundle@v2
      id: create-bundle
      with:
        bundle-path: ${{ steps.download-bundle.outputs.bundle-path }}
        packs: "codeql/csharp-all,codeql/csharp-queries" 
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release
      
    - uses: actions/upload-artifact@v3
      with:
        name: codeql-bundle.tar.gz
        path: ${{ steps.create-bundle.outputs.output-path }}
